### PR TITLE
Add test for private github email fetching

### PR DESCRIPTION
**Pull request by kairichard**
Using the new structure from https://github.com/authlib/loginpass/pull/37 and the modified `Github` remote from https://github.com/authlib/loginpass/pull/36 I added tests related to https://github.com/authlib/loginpass/issues/32 which exposed a suboptimal `self.get` where the `token` had to be re-fetched. 

So this PR does the following things:
- add tests for `Github` private email fetching
- pass the token along with fetching the user's private email

### CODE REVIEW

**Comment by lepture** [comment]
In this way, we can only test the missing email case. How about the case with email address in `/user`?

**Comment by kairichard** [comment]
This might be a shortcoming of the test-setup but I view the test as being inclusive of the happy-path, meaning the current execution part "covers" both parts. A more complete setup would be to also introduce `01_public_email`  and `02_private_email` inside the `test/data/github` folder. 
Let me know what you think.

**Comment by kairichard** [comment]
@lepture I changed to PR to separate the two cases and cover both scenarios. Let me know what you think.

**Comment by kairichard** [comment]
@lepture The change is now covering all cases - hope you get the time soon to review this.

**Pull request closed without merging**
